{
 "title": "Registros por año",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Empresas con Mayor Exportación por Productos",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    e.NOMCON AS empresa,\n    e.PAISCON AS pais,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nGROUP BY \n    e.NOMCON, e.PAISCON\nORDER BY \n    total_registros DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Empresas con Mayor Diversidad de Productos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    e.NOMCON AS empresa,\n    COUNT(DISTINCT e.PROD) AS total_productos\nFROM \n    tabla_empresas e\nGROUP BY \n    e.NOMCON\nORDER BY \n    total_productos DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Análisis por Actores",
   "type": "barchart",
   "description": "Relaciona ACTOR con el total de registros para identificar las empresas o categorías más importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    CASE\n        WHEN e.ACTOR = 'P' THEN 'Privado'\n        WHEN e.ACTOR = 'E' THEN 'Estatal'\n        ELSE 'Cooperativa'\n    END AS actor,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nGROUP BY \n    actor\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Número de empresas por país",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    e.PAISCON AS pais,\n    COUNT(DISTINCT e.NOMCON) AS total_empresas\nFROM \n    tabla_empresas e\nGROUP BY \n    e.PAISCON\nORDER BY \n    total_empresas DESC;\n"
    }
   ]
  },
  {
   "title": " Top 5 de Empresas ",
   "type": "barchart",
   "description": "Empresas con mayor participación",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    e.NOMCON AS empresa,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nGROUP BY \n    e.NOMCON\nORDER BY \n    total_registros DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Proporcion de productos exportados en Asia",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    CASE\n        WHEN e.PROD = 'H' THEN 'Hierro'\n        WHEN e.PROD = 'C' THEN 'Cobre'\n        WHEN e.PROD = 'H M E' THEN 'Hierro y Metales Especiales'\n        WHEN e.PROD = 'A' THEN 'Aluminio'\n        WHEN e.PROD = 'P' THEN 'Plomo'\n        WHEN e.PROD = 'Z' THEN 'Zinc'\n        WHEN e.PROD = 'O' THEN 'Oro'\n        ELSE 'Otro'\n    END AS producto,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nJOIN \n    tabla_paises p ON e.PAISCON = p.PAIS\nWHERE \n    p.CONTINENTE = 'ASIA'\nGROUP BY \n    producto\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Proporcion de productos exportados en America",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    CASE\n        WHEN e.PROD = 'H' THEN 'Hierro'\n        WHEN e.PROD = 'C' THEN 'Cobre'\n        WHEN e.PROD = 'H M E' THEN 'Hierro y Metales Especiales'\n        WHEN e.PROD = 'A' THEN 'Aluminio'\n        WHEN e.PROD = 'P' THEN 'Plomo'\n        WHEN e.PROD = 'Z' THEN 'Zinc'\n        WHEN e.PROD = 'O' THEN 'Oro'\n        ELSE 'Otro'\n    END AS producto,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nJOIN \n    tabla_paises p ON e.PAISCON = p.PAIS\nWHERE \n    p.CONTINENTE = 'AMERICA'\nGROUP BY \n    producto\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Proporcion de productos exportados en Europa",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    CASE\n        WHEN e.PROD = 'H' THEN 'Hierro'\n        WHEN e.PROD = 'C' THEN 'Cobre'\n        WHEN e.PROD = 'H M E' THEN 'Hierro y Metales Especiales'\n        WHEN e.PROD = 'A' THEN 'Aluminio'\n        WHEN e.PROD = 'P' THEN 'Plomo'\n        WHEN e.PROD = 'Z' THEN 'Zinc'\n        WHEN e.PROD = 'O' THEN 'Oro'\n        ELSE 'Otro'\n    END AS producto,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nJOIN \n    tabla_paises p ON e.PAISCON = p.PAIS\nWHERE \n    p.CONTINENTE = 'EUROPA'\nGROUP BY \n    producto\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Exportaciones por Tipo de Mineral",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    n.TIPO_MINERAL AS tipo_mineral,\n    COUNT(*) AS total_registros\nFROM \n    tabla_nandina n\nGROUP BY \n    tipo_mineral\nORDER BY \n    total_registros DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Exportaciones por Continente",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 36 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    p.CONTINENTE AS continente,\n    COUNT(e.PAISCON) AS total_registros\nFROM \n    tabla_empresas e\nJOIN \n    tabla_paises p ON e.PAISCON = p.PAIS\nGROUP BY \n    p.CONTINENTE\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": " Exportaciones por Producto y Año",
   "type": "barchart",
   "description": "Relaciona los productos exportados con los años para analizar tendencias en exportaciones a lo largo del tiempo.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    e.ANIO AS año,\n    CASE\n        WHEN e.PROD = 'H' THEN 'Hierro'\n        WHEN e.PROD = 'C' THEN 'Cobre'\n        WHEN e.PROD = 'A' THEN 'Aluminio'\n        ELSE 'Otro'\n    END AS producto,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nGROUP BY \n    año, producto\nORDER BY \n    año ASC, total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Top  10 Países con Más Registros",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    COALESCE(PAISCON, 'Desconocido') AS pais,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas\nGROUP BY \n    PAISCON\nORDER BY \n    total_registros DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Productos Exportados",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    CASE\n        WHEN e.PROD = 'H' THEN 'Hierro'\n        WHEN e.PROD = 'C' THEN 'Cobre'\n        WHEN e.PROD = 'H M E' THEN 'Hierro y Metales Especiales'\n        WHEN e.PROD = 'A' THEN 'Aluminio'\n        WHEN e.PROD = 'P' THEN 'Plomo'\n        WHEN e.PROD = 'Z' THEN 'Zinc'\n        WHEN e.PROD = 'O' THEN 'Oro'\n        ELSE 'Otro'\n    END AS producto,\n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas e\nGROUP BY \n    producto\nORDER BY \n    total_registros DESC;\n"
    }
   ]
  },
  {
   "title": "Registros por Año",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT \n    ANIO, \n    COUNT(*) AS total_registros\nFROM \n    tabla_empresas\nGROUP BY \n    ANIO\nORDER BY \n    ANIO ASC;\n"
    }
   ]
  }
 ]
}